server:
  port: 8083

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/v1/auth/**, /api/v1/users/**

        - id: url-shortener-service
          uri: lb://url-shortener-service
          predicates:
            - Path=/api/v1/urls/**, /r/{shortUrl}

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/